In [ ]:
import pandas as pd
data = pd.read_csv("/content/Churn_Modelling.csv")

In [ ]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
data.info

<bound method DataFrame.info of       RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfP

In [ ]:
data.drop(columns =['RowNumber','CustomerId','Surname'],inplace = True)

In [ ]:
data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [ ]:
data['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [ ]:
data['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [ ]:
data = pd.get_dummies(data,columns=['Geography','Gender'],drop_first=True)

In [ ]:
data.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0               1        101348.88       1                  0   
1               1        112542.58       0                  0   
2               0        113931.57       1                  0   
3               0         93826.63       0                  0   
4               1         79084.10       0                  0   

   Geography_Spain  Gender_Male  
0                0            0  
1                1            0  
2                0            0  
3                0            0  
4                1            0

In [ ]:
data.columns

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Geography_Germany',
       'Geography_Spain', 'Gender_Male'],
      dtype='object')

In [ ]:
X = data.drop(columns=['Exited'])

In [ ]:
y=data['Exited']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test =train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_trf=scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)

In [ ]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(3,activation ='sigmoid',input_dim=11))
model.add(Dense(1,activation ='sigmoid'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 36        
                                                                 
 dense_1 (Dense)             (None, 1)                 4         
                                                                 
Total params: 40 (160.00 Byte)
Trainable params: 40 (160.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(optimizer='Adam',loss='binary_crossentropy')

In [ ]:
history = model.fit(X_train,y_train,batch_size=50,epochs=10)

Epoch 1/10
160/160 [==============================] - 1s 2ms/step - loss: 0.6011
Epoch 2/10
160/160 [==============================] - 0s 2ms/step - loss: 0.5788
Epoch 3/10
160/160 [==============================] - 0s 2ms/step - loss: 0.5666
Epoch 4/10
160/160 [==============================] - 0s 2ms/step - loss: 0.5570
Epoch 5/10
160/160 [==============================] - 0s 2ms/step - loss: 0.5488
Epoch 6/10
160/160 [==============================] - 0s 2ms/step - loss: 0.5416
Epoch 7/10
160/160 [==============================] - 0s 2ms/step - loss: 0.5354
Epoch 8/10
160/160 [==============================] - 0s 2ms/step - loss: 0.5299
Epoch 9/10
160/160 [==============================] - 0s 2ms/step - loss: 0.5252
Epoch 10/10
160/160 [==============================] - 0s 2ms/step - loss: 0.5212


In [ ]:
model.layers[1].get_weights()

[array([[ 0.6824349 ],
        [-1.3641055 ],
        [-0.98251855]], dtype=float32),
 array([-0.9468377], dtype=float32)]

In [ ]:
y_pred =model.predict(X_test)

63/63 [==============================] - 0s 2ms/step


In [ ]:
y_pred

array([[0.22323352],
       [0.22323352],
       [0.22323352],
       ...,
       [0.22323352],
       [0.22323352],
       [0.22323352]], dtype=float32)

In [ ]:
import numpy as np


In [ ]:
final_pred = np.where(y_pred>=0.5,1,0)

In [ ]:
final_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(final_pred,y_test)

0.7975